vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: '/images/documents'
            upload_destination: '%kernel.project_dir%/public/images/documents'
            namer:
                service: vich_uploader.namer_uniqid

            
            